// <auto-generated />
using GestionContactos.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionContactos.Infrastructure.Migrations
{
    [DbContext(typeof(GestionContactosContext))]
    partial class GestionContactosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionContactos.Domain.Entities.DatoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Datos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "De León",
                            Correo = "dleonRonny@gmail.com",
                            Nombre = "Ronny",
                            Telefono = "809-865-2927"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Almonte",
                            Correo = "PipeAlm@gmail.com",
                            Nombre = "Pipe",
                            Telefono = "829-092-6767"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Perez",
                            Correo = "DiegoPPerez",
                            Nombre = "Diego",
                            Telefono = "809-000-0000"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
